baseUrl: "/"
languageCode: "ru"
title: "СУБД"
theme: "tech-template"

relativeURLs: true
disableKinds:
- 404
- RSS
metadataFormat: "yaml"

blackfriday:
  sourceRelativeLinksEval: true

params:
  author: "Стрелков Никита / Стулов Игорь"
  email: "n.strelkov@corp.mail.ru / i.stulov@corp.mail.ru"
  description: "Лекции для Технопарка по курсу СУБД"
  highlightTheme: "idea"
  useMath: false
  favicon: "common/lecture.png"
