baseURL: "/"
languageCode: "ru"
title: "СУБД"
theme: shower
relativeURLs: true

disableRSS: true
disable404: true
metadataFormat: "yaml"

params:
  author: "Навроцкий Артем"
  agent: navrotskiy@corp.mail.ru
