baseUrl: "/"
languageCode: "ru"
title: "СУБД"
theme: "technopark-theme-template"

relativeURLs: true
disableKinds:
- 404
- RSS
metadataFormat: "yaml"

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  author: "Алехин Владислав"
  email: "v.alehin@corp.mail.ru"
  description: "Лекции для Технопарка по курсу СУБД"
  highlightTheme: "idea"
  useMath: false
  favicon: "common/lecture.png"
