baseUrl: "/"
languageCode: "ru"
title: "СУБД"
theme: shower

canonifyURLs: false
relativeURLs: true
disableRSS: true
disable404: true
metadataFormat: "yaml"

blackfriday:
  sourceRelativeLinksEval: true

params:
  author: "Навроцкий Артем"
  agent: navrotskiy@corp.mail.ru
  description: "Лекции для Технопарка по курсу СУБД"
