version: "3.9"
services:
  postgres:
    container_name: techdb
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: "techdb"
      POSTGRES_USER: "techdb"
      POSTGRES_PASSWORD: "techdb"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./postgres/init/:/docker-entrypoint-initdb.d
      - ./postgres:/var/lib/postgresql/data
    command: postgres -c config_file=/var/lib/postgresql/data/postgresql.conf
    ports:
      - "5432:5432"
